import type { Metadata } from "next";
import SubpageLayout from "@/components/SubpageLayout";
import { INK, MUTED, VIOLET } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Terms of Service | Alpine Due Diligence",
};

export default function TermsPage() {
  return (
    <SubpageLayout>
      <main className="flex-1 mx-auto max-w-3xl px-6 py-16 w-full">
        <h1 className="font-heading font-emphasis text-3xl" style={{ color: INK }}>Terms of Service</h1>
        <p className="mt-2 text-sm font-mono" style={{ color: MUTED }}>Last updated: February 15, 2026</p>

        <div className="mt-10 space-y-8 text-base leading-relaxed" style={{ color: INK }}>
          <section>
            <h2 className="font-heading font-emphasis text-lg" style={{ color: INK }}>1. Service Description</h2>
            <p className="mt-3">
              Alpine Due Diligence Inc. (&ldquo;Alpine&rdquo;) provides an operational due diligence platform (&ldquo;Platform&rdquo;) that supports document analysis, gap assessment, regulatory verification, and report generation for institutional investors. The Platform is accessed via web application at alpinedd.com.
            </p>
          </section>

          <section>
            <h2 className="font-heading font-emphasis text-lg" style={{ color: INK }}>2. Account Responsibilities</h2>
            <p className="mt-3">
              You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate and complete registration information and promptly update it if it changes. You agree to notify Alpine immediately of any unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="font-heading font-emphasis text-lg" style={{ color: INK }}>3. Acceptable Use</h2>
            <p className="mt-3">You agree to use the Platform only for lawful purposes related to operational due diligence. You may not:</p>
            <ul className="mt-2 space-y-1.5 list-disc pl-5">
              <li>Upload documents you do not have authorization to process</li>
              <li>Attempt to access other organizations&apos; data or accounts</li>
              <li>Reverse engineer, decompile, or disassemble the Platform</li>
              <li>Use the Platform to compete with Alpine or build a competing product</li>
              <li>Share account credentials with unauthorized parties</li>
            </ul>
          </section>

          <section>
            <h2 className="font-heading font-emphasis text-lg" style={{ color: INK }}>4. Data Ownership</h2>
            <p className="mt-3">
              <strong>Your Data:</strong> You retain full ownership of all documents you upload and all reports generated from your documents. Alpine does not claim any ownership interest in your data.
            </p>
            <p className="mt-3">
              <strong>Alpine&apos;s Property:</strong> Alpine retains ownership of the Platform, its eight-chapter ODD framework, analytical methodologies, risk observation libraries, report templates, and all underlying technology. These are proprietary to Alpine and may not be copied or reproduced.
            </p>
          </section>

          <section>
            <h2 className="font-heading font-emphasis text-lg" style={{ color: INK }}>5. Confidentiality</h2>
            <p className="mt-3">
              All documents uploaded to the Platform are treated as confidential. Alpine will not disclose your documents or analysis results to any third party except as required by law or as described in our Privacy Policy. Alpine processes documents using Anthropic&apos;s commercial API under a Data Processing Agreement with Zero Data Retention.
            </p>
          </section>

          <section>
            <h2 className="font-heading font-emphasis text-lg" style={{ color: INK }}>6. Disclaimer &mdash; Not Investment Advice</h2>
            <p className="mt-3">
              Alpine provides operational due diligence analysis tools. <strong>The Platform does not provide investment advice, legal advice, or compliance opinions.</strong> Reports generated by the Platform are analytical tools to assist your due diligence process. All investment decisions remain your responsibility. Alpine is not registered as an investment adviser, broker-dealer, or legal services provider.
            </p>
          </section>

          <section>
            <h2 className="font-heading font-emphasis text-lg" style={{ color: INK }}>7. Limitation of Liability</h2>
            <p className="mt-3">
              To the maximum extent permitted by law, Alpine&apos;s total liability for any claims arising from your use of the Platform shall not exceed the amounts paid by you to Alpine in the twelve (12) months preceding the claim. Alpine shall not be liable for any indirect, incidental, special, consequential, or punitive damages.
            </p>
          </section>

          <section>
            <h2 className="font-heading font-emphasis text-lg" style={{ color: INK }}>8. Service Availability</h2>
            <p className="mt-3">
              Alpine will use commercially reasonable efforts to maintain Platform availability. However, we do not guarantee uninterrupted access. The Platform may be temporarily unavailable for maintenance, updates, or circumstances beyond our control.
            </p>
          </section>

          <section>
            <h2 className="font-heading font-emphasis text-lg" style={{ color: INK }}>9. Termination</h2>
            <p className="mt-3">
              Either party may terminate this agreement at any time. Upon termination, your access to the Platform will be revoked. You may request export of your data and reports prior to termination. Alpine will retain audit logs as required by our data retention policy.
            </p>
          </section>

          <section>
            <h2 className="font-heading font-emphasis text-lg" style={{ color: INK }}>10. Governing Law</h2>
            <p className="mt-3">
              These Terms are governed by the laws of Canada and the Province of Ontario. Any disputes arising from these Terms shall be resolved in the courts of Ontario.
            </p>
          </section>

          <section>
            <h2 className="font-heading font-emphasis text-lg" style={{ color: INK }}>11. Changes to Terms</h2>
            <p className="mt-3">
              Alpine may update these Terms from time to time. We will notify you of material changes via email or through the Platform. Continued use of the Platform after changes constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="font-heading font-emphasis text-lg" style={{ color: INK }}>12. Contact</h2>
            <p className="mt-3">
              For questions about these Terms, contact us at{" "}
              <a href="mailto:azhang@alpinedd.com" className="hover:underline" style={{ color: VIOLET }}>azhang@alpinedd.com</a>.
            </p>
          </section>
        </div>
      </main>
    </SubpageLayout>
  );
}
